# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 003f2dccc550d14b6637e372ca80142fb8a08df5f2b9c444ec6223f63ea7da30d0bb4d92373e1c9cff7cb55e7797d87d4d3edf6370ef97d1d9b053edfb332ab3

test:
  secret_key_base: 45ea70694ce0d635420138cb92f18a026c3ad4916ce955b804f7b6968ea278ec1e7b16d9ecf2b7a4b906627cf87fb2b646d59bfb1fa9b629237571d53656764e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
